name: CMake
on: push

jobs:
  build-linux:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
        cxx_compiler: [g++-10] #, clang++-11, clang++-12]

    steps:
      - name: Install dependencies
        run: |
          wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
          sudo wget -qP /etc/apt/sources.list.d https://packages.lunarg.com/vulkan/lunarg-vulkan-focal.list
          sudo apt-get update
          sudo apt-get install vulkan-sdk xorg-dev

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure CMake
        run: cmake
          -B ${{github.workspace}}/build
          -D CMAKE_CXX_COMPILER=${{matrix.cxx_compiler}}

      - name: Build lib
        run: cmake
          --build ${{github.workspace}}/build
          --config ${{matrix.build_type}}

  build-windows:
    runs-on: windows-latest
    env:
      VULKAN_SDK: C:/VulkanSDK

    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    steps:
      - name: Install dependencies
        run: |
          iwr https://sdk.lunarg.com/sdk/download/latest/windows/vulkan-sdk.exe -outfile vulkan-sdk.exe
          ./vulkan-sdk install --accept-licenses --confirm-command --root $env:VULKAN_SDK

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure CMake
        run: cmake
          -B ${{github.workspace}}/build

      - name: Build lib
        run: cmake
          --build ${{github.workspace}}/build
          --config ${{matrix.build_type}}
