name: Documentation

on: push

jobs:
  build-doc:
    runs-on: ubuntu-latest

    steps:
      - name: install dependencies
        run: |
          wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
          sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.2.182-focal.list https://packages.lunarg.com/vulkan/1.2.182/lunarg-vulkan-1.2.182-focal.list
          sudo apt update
          sudo apt install vulkan-sdk libpthread-stubs0-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev xorg-dev doxygen

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure CMake
        run: cmake
          -B ${{github.workspace}}/build
          -DBUILD_DOCUMENTATION=ON

      - name: Build doc
        run: cmake
          --build ${{github.workspace}}/build
          --target doc

      - name: Check no warnings
        run: '! test -s ${{github.workspace}}/build/doxygen-warnings.log'

      - uses: actions/upload-artifact@v2
        with:
          name: doc
          path: ${{github.workspace}}/build/html
          retention-days: 7
