name: Documentation

on: [push, workflow_dispatch]

env:
  refsDocSaved: |
    refs/heads/main
    refs/heads/dev

jobs:
  build-doc:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
          sudo wget -qP /etc/apt/sources.list.d https://packages.lunarg.com/vulkan/lunarg-vulkan-focal.list
          sudo apt-get update
          sudo apt-get install vulkan-sdk xorg-dev doxygen

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure CMake
        run: cmake
          -B ${{github.workspace}}/build
          -D BUILD_DOCUMENTATION=ON

      - name: Build doc
        run: cmake
          --build ${{github.workspace}}/build
          --target doc

      - name: Check no warnings
        if: ${{github.event_name != 'workflow_dispatch'}}
        run: '! test -s ${{github.workspace}}/build/doxygen-warnings.log'

      - uses: actions/upload-artifact@v2
        if: ${{contains(env.refsDocSaved, github.ref)
          || github.event_name == 'workflow_dispatch'}}
        with:
          name: doc
          path: |
            ${{github.workspace}}/build/html
            ${{github.workspace}}/build/doxygen-warnings.log
          retention-days: 1
